services:
    postgres:
        container_name: app_db
        restart: always
        image: 'postgres:15-alpine'
        ports:
            - '5555:5432'
        environment:
            TZ: 'America/Sao_Paulo'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-db}'
            POSTGRES_USER: '${DB_USERNAME:-user}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'app_db:/var/lib/postgresql/data:rw'
        networks:
            - app_network
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${DB_USERNAME:-user} -d ${DB_DATABASE:-db}"
                ]
            interval: 10s
            timeout: 5s
            retries: 3

volumes:
    app_db:
        driver: local

networks:
    app_network:
        driver: bridge
