export enum UserErrorEnum {
  ALREADY_EXISTS = 'error_already_exists',
  CREATE_USER = 'error_create_user',
  EXISTS_USER_BY_EMAIL = 'error_exists_user_by_email',
  FIND_USER_BY_EMAIL = 'error_find_user_by_email',
  FIND_USER_BY_ID = 'error_find_user_by_id',
  FIND_ALL_USERS = 'error_find_all_users',
  DELETE_USER = 'error_delete_user',
  UPDATE_USER = 'error_update_user',
  ARCHIVE_USER = 'error_archive_user',
  ACTIVATE_USER = 'error_activate_user',
  CHANGE_PASSWORD = 'error_change_password',
  HASH_PASSWORD = 'error_hash_password',
  COMPARE_PASSWORD = 'error_compare_password',
  USER_NOT_FOUND = 'error_user_not_found',
  PASSWORD_NOT_MATCH = 'error_password_not_match',
}
